
function getCurrentWave(){
	allwaves = [
		[12,0,0,0,0,0],
		[25,0,0,0,0,0],
		[24,5,0,0,0,0],
		[10,15,0,0,0,0],
		[30,25,0,0,0,0],
		[0,5,15,0,0,0],
		[0,80,0,0,0,0],
		[70,70,0,0,0,0],
		[0,50,15,0,0,0],
		[0,0,35,0,0,0],
		[0,0,0,15,0,0],
		[0,25,25,3,0,0],
		[40,75,28,0,0,0],
		[0,0,0,28,0,0],
		[0,30,60,0,0,0],
		[0,70,75,0,0,0],
		[0,140,45,0,0,0],
		[0,30,25,27,0,0],
		[0,0,90,0,0,0],
		[0,0,24,48,0,0],
		[0,10,85,35,0,0],
		[0,0,0,45,0,0],
		[0,0,35,64,0,0],
		[0,30,50,42,0,0],
		[0,0,70,53,0,0],
		[0,0,0,85,0,0],
		[0,0,0,0,20,0],
		[0,0,45,55,0,0],
		[0,0,0,125,19,0],
		[0,0,250,0,0,0],
		[0,10,55,0,27,0],
		[0,0,25,20,23,0],
		[0,0,0,150,0,0],
		[0,0,35,35,25,0],
		[0,0,85,110,0,0],
		[0,0,0,115,35,0],
		[0,0,0,0,59,0],
		[0,0,0,220,0,0],
		[50,50,50,50,40,0],
		[0,0,0,0,80,0],
		[0,0,0,0,20,40],
		[0,0,0,20,30,30],
		[0,0,0,150,60,40],
		[0,0,0,0,120,0],
		[0,0,0,0,0,120],
		[0,0,0,59,60,60],
		[0,0,0,79,70,40],
		[0,0,0,70,80,80],
		[0,0,0,99,80,70],
		[0,0,0,0,99,100],		
	];
	return allwaves[global.level - 1];
}

function getComment() {
	roundcomments = [
		"Welcome to Monkey Defense Madness! Stop the balloons escaping by building towers next to the maze. As you get more money build more towers or upgrading existing ones.",
		"That was too easy, press 'Start Round' to play the next round.",
		"Still super easy, you didn't miss any did you?",
		"Blue balloons move faster and have red balloons inside them.",
		"balloons start spawn a bit faster every 10 rounds.",
		"Green balloons move even faster and have blue balloons inside them!",
		"Lots of blue ones coming up. Hope you're ready...",
		"The dart tower piercing upgrade allows darts to pop up to 2 balloons each.",
		"Ice towers work best with bomb towers nearby.",
		"Are you ready for a whole bunch of greens? The balloons are going to spawn just a bit faster from now on.",
		"Yellow balloons are - you guessed it, even bigger and even faster and have greens inside them.",
		"Tower upgrades are usually a better option than just adding more towers.",
		"Tower defense is about what towers you use and where you put them.",
		"The super monkey tower is not a joke, he really is poptastic!",
		"You lose one life for every balloon that escapes. So a blue balloon costs you two lives, a green one three lives etc.",
		"This game took quite a while to make. I really appreciate that you are playing it!",
		"Relax a bit, there are no yellow balloons in the next level.",
		"Have you played Harvest Earth? Probably...if you are Lyz",
		"A whole bunch of greens coming up.",
		"Too easy. Let's step this up a bit. The balloons are spawing faster now too!",
		"Place your towers so that they can be shooting at something for a long time, corners are good.",
		"Ready for 45 straight yellows?",
		"Lots of yellows and greens - that should take care of you...",
		"There's a secret ENDLESS mode at the end if you make it...oops, it's not secret anymore.",
		"The oldest living land animal on earth is a 192-year-old tortoise named Jonathan.",
		"Tack towers are really useful for thinning out the crowds - get the speed upgrade for extra effectiveness.",
		"Black balloons are nasty - they are small but contain 2 yellows inside them. Oh did I mention they are IMMUNE TO BOMBS?!",
		"When you sell a tower, you get 80% of what you paid for it, including all the upgrade money you spent.",
		"Lots and lots of yellow and black balloons. Good luck!",
		"Next is a cash round - pop hundreds and hundreds of greens to top up your money. The balloons will spawn even faster!",
		"Monkeys aren't so good at shooting at things moving to their left. Something about being right handed I guess.",
		"The good thing about black balloons is that they move slower than yellows.",
		"A - lot of yellows.",
		"Monkeys are intelligent communicators and can tell each other secrets.",
		"Build as many monkeys as you can. You're going to need them!",
		"Upgrading a super monkey isn't always required. Sometimes letting them focus on what's close by is better.",
		"Just black balloons coming up. Lots of 'em.",
		"Just around the corner there are a throng of yellow balloons waiting to have a go...",
		"Just for fun, there are some of each colour balloon in the next level. Enjoy popping those easy reds for a change.",
		"80 black balloons coming up and all future balloons will be spawning faster!",
		"It's important to not lose early lives, because the levels are only getting harder.",
		"White balloons are IMMUNE TO FREEZING - and they also have 2 yellows inside them.",
		"How many monkeys does it take to make a Super Monkey? That stuff will keep you up at night.",
		"Lots and lots and lots of black balloons. More than ever.",
		"Lots and lots and lots of WHITE balloons. More than ever.",
		"Lots of white, black, and yellow balloons. The next level is going to hurt.",
		"You still playing? Thank you! You're almost to the last end!",
		"You got any Super Monkeys yet? Are they really worth all that money?",
		"Its ok if you don't pass this level. Really it is. Just try again. Its the effort that counts.",
		"This is the last level. There are TONS AND TONS of black AND white balloons coming. Hope you have lots of lives left...",
		"You did it! Thank you for playing! Press Start Round for ENDLESS MODE! HP is reset! Black and white balloons spawn and move faster and faster as time passes. Get ready!",
	];
	return roundcomments[global.level];
}